name: Build and Upload Simple Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: List files in the repository to show the current state
      - name: List files in the repository
        run: |
          echo "Listing files in the repository:"
          ls -R  # Lists all files and directories recursively

      # Step 3: Build the application (simulated by creating a file)
      - name: Build the application
        run: |
          echo "Building the application"
          mkdir -p dist  # Create a directory to store the build
          echo "Build version 1.0" > dist/version.txt  # Create a simple file to simulate build output

      # Step 4: List files again after build to show the created artifact
      - name: List files after build
        run: |
          echo "Listing files after the build:"
          ls -R  # Lists all files and directories recursively again

      # Step 5: Upload the created file as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/version.txt  # Path to the created file
