name: Build and Upload Simple Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build the application (for example, npm install and npm run build)
      - name: Build the application
        run: |
          echo "Building the application"
          mkdir -p dist  # Create a directory to store the build
          echo "Build version 1.0" > dist/version.txt  # Create a simple file to simulate build output

      # Step 3: Upload the created file as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/version.txt  # Path to the created file
