name: Build, Test, and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (can be replaced with other setups like Python, Java, etc.)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify Node.js version here

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the application (if applicable, like for front-end apps)
      - name: Build the application
        run: npm run build

      # Step 5: Run tests
      - name: Run tests
        run: npm test

      # Step 6: Upload build artifacts (e.g., compiled files, test reports)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist  # Adjust the path to your build output directory

      # Step 7: Optionally, notify success or failure (e.g., email, Slack, etc.)
      - name: Notify success
        if: success()
        run: echo "Build, Test, and Artifact Upload Completed Successfully"
